services:
  - name: lightdash
    type: web
    env: node
    plan: free
    buildCommand: "corepack enable && pnpm install --frozen-lockfile"
    healthCheckPath: /api/v1/health
    envVars:
      - key: LIGHTDASH_SECRET
        generateValue: true
      - key: PGPASSWORD
        fromDatabase:
          name: lightdash-db
          property: password
      - key: PGHOST
        fromDatabase:
          name: lightdash-db
          property: host
      - key: PGUSER
        fromDatabase:
          name: lightdash-db
          property: user
      - key: PGDATABASE
        fromDatabase:
          name: lightdash-db
          property: database
      - key: PORT
        value: 8080
      - key: LIGHTDASH_INSTALL_TYPE
        value: RENDER
      - key: NODE_ENV
        value: production
    startCommand: "./node_modules/.bin/dbt deps --no-version-check && ./node_modules/.bin/dbt-lightdash-v2 migrate && ./node_modules/.bin/dbt-lightdash-v2 start"

databases:
  - name: lightdash-db
    plan: free