services:
  - name: lightdash
    type: web
    env: docker
    plan: free
    healthCheckPath: /api/v1/health
    dockerfilePath: ./Dockerfile
    envVars:
      - key: LIGHTDASH_SECRET
        generateValue: true
      - key: PGPASSWORD
        fromDatabase:
          name: lightdash-db
          property: password
      - key: PGHOST
        fromDatabase:
          name: lightdash-db
          property: host
      - key: PGUSER
        fromDatabase:
          name: lightdash-db
          property: user
      - key: PGDATABASE
        fromDatabase:
          name: lightdash-db
          property: database
      - key: PORT
        value: 8080
      - key: LIGHTDASH_INSTALL_TYPE
        value: RENDER
      - key: NODE_ENV
        value: production
      # The entrypoint script in the Dockerfile will handle migrations and starting the app
      - key: LIGHTDASH_DBT_PROFILES_DIR
        value: /tmp/
      - key: LIGHTDASH_PROJECT_TYPE
        value: dbt
      - key: LIGHTDASH_DBT_TARGET
        value: dev

databases:
  - name: lightdash-db
    plan: free