services:
  - name: lightdash
    type: web
    env: node
    plan: free
    healthCheckPath: /api/v1/health
    envVars:
      - key: LIGHTDASH_SECRET
        generateValue: true
      - key: PGPASSWORD
        fromDatabase:
          name: lightdash-db
          property: password
      - key: PGHOST
        fromDatabase:
          name: lightdash-db
          property: host
      - key: PGUSER
        fromDatabase:
          name: lightdash-db
          property: user
      - key: PGDATABASE
        fromDatabase:
          name: lightdash-db
          property: database
      - key: PORT
        value: 8080
      - key: LIGHTDASH_INSTALL_TYPE
        value: RENDER
      - key: NODE_ENV
        value: production
    preDeployCommand: |-
      export DATABASE_URL=postgresql://${PGUSER}:${PGPASSWORD}@${PGHOST}/${PGDATABASE}
      dbt deps --no-version-check
      dbt-lightdash-v2 migrate
    startCommand: "dbt-lightdash-v2 start"

databases:
  - name: lightdash-db
    plan: free