services:
  - name: lightdash
    type: web
    env: docker
    plan: free
    healthCheckPath: /api/v1/health
    dockerfilePath: ./Dockerfile
    envVars:
      # --- Lightdash Base Config ---
      - key: LIGHTDASH_SECRET
        generateValue: true
      - key: PORT
        value: 8080
      - key: NODE_ENV
        value: production
      # --- Postgres DB Config (from Render) ---
      - key: PGPASSWORD
        fromDatabase:
          name: lightdash-db
          property: password
      - key: PGHOST
        fromDatabase:
          name: lightdash-db
          property: host
      - key: PGUSER
        fromDatabase:
          name: lightdash-db
          property: user
      - key: PGDATABASE
        fromDatabase:
          name: lightdash-db
          property: database
      # --- dbt Cloud Project Config ---
      - key: LIGHTDASH_PROJECT_TYPE
        value: dbt_cloud_cli
      - key: DBT_CLOUD_PROJECT_ID
        value: "70471823493419"
      - key: DBT_CLOUD_ENVIRONMENT_ID
        value: "70471823469537"
      - key: DBT_CLOUD_API_KEY
        sync: false # This will be set manually in the Render UI

databases:
  - name: lightdash-db
    plan: free